#!/usr/bin/env bash

set -euox pipefail

TEMP_DIR=$(mktemp -d)

# Defer cleanup
cleanup() {
  ls $TEMP_DIR
  rm -rf "$TEMP_DIR"
}
trap cleanup EXIT

# Clear previous `dist`
if [ -d dist ]; then
  rm -rf dist
fi

# Writes new files to `dist`
pnpm build
cp -r dist/* "$TEMP_DIR"

# Checkout `gh-pages`
if git show-ref --quiet refs/heads/gh-pages; then
  git checkout gh-pages
else
  git checkout --orphan gh-pages
fi

# Remove all git tracked files
git rm -rf .
git checkout main -- .gitignore

# Copy over built assets
cp -r "$TEMP_DIR"/* .

# Add them and commit it
git add .
git commit -m "gh-pages deploy"
git push

# Return to the main branch
git checkout main
